- name: xray
  repo: XTLS/Xray-core
  version: 25.3.6
  white_list:
  - - linux-64
  - - linux-arm64
  black_list:
  - dgst
- name: v2rayn
  repo: 2dust/v2rayN
  version: 7.10.5
  white_list:
  - - v2rayN-windows-64.zip
- name: v2rayng
  repo: 2dust/v2rayNG
  version: 1.9.46
  white_list:
  - - arm64-v8a
- name: mosdns
  repo: IrineSistiana/mosdns
  version: 5.3.3
  white_list:
  - - linux-amd64
- name: cmfa
  repo: MetaCubeX/ClashMetaForAndroid
  version: 2.11.8
  white_list:
  - - arm64-v8a
- name: clashn
  repo: 2dust/clashN
  version: '2.22'
  white_list:
  - - clashN.zip
- name: pure_live
  repo: Jackiu1997/pure_live
  version: 1.1.0
  white_list:
  - - android
