- name: xray
  repo: XTLS/Xray-core
  version: 25.7.26
  white_list:
  - - linux-64
  - - linux-arm64
  black_list:
  - dgst
- name: v2rayn
  repo: 2dust/v2rayN
  version: 7.12.7
  white_list:
  - - v2rayN-windows-64.zip
- name: v2rayng
  repo: 2dust/v2rayNG
  version: 1.10.8
  white_list:
  - - arm64-v8a
- name: mosdns
  repo: IrineSistiana/mosdns
  version: 5.3.3
  white_list:
  - - linux-amd64
