name: clean
on:
  workflow_dispatch:
jobs:
  build:
    name: clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v3
      - name: Clean commits
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest_branch
          git commit -am "Clean commits"
          git branch -D main
          git branch -m main
          git push -f origin main
