name: sync
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
      types: started
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check and release
        run: |
          push=0
          git config user.name "771073216"
          git config user.email "771073216@qq.com"
          xray_latest=$(wget -qO- "https://api.github.com/repos/XTLS/Xray-core/tags" | awk -F '"' '/name/ {print $4}' | head -n 1 | tr -d 'v')
          v2rayn_latest=$(wget -qO- "https://api.github.com/repos/2dust/v2rayN/tags" | awk -F '"' '/name/ {print $4}' | head -n 1)
          v2rayng_latest=$(wget -qO- "https://api.github.com/repos/2dust/v2rayNG/tags" | awk -F '"' '/name/ {print $4}' | head -n 1)
          caddy_latest=$(wget -qO- "https://api.github.com/repos/caddyserver/caddy/tags" | awk -F '"' '/name/ {print $4}' | head -n 1 | tr -d 'v')
          anxray_latest=$(wget -qO- "https://api.github.com/repos/XTLS/AnXray/tags" | awk -F '"' '/name/ {print $4}' | head -n 1)
          sagernet_latest=$(wget -qO- "https://api.github.com/repos/SagerNet/SagerNet/releases/latest" | awk -F '"' '/tag_name/ {print $4}')
          xray_local=$(awk '/\<xray\>/ {print$2}' version)
          v2rayn_local=$(awk '/\<v2rayn\>/ {print$2}' version)
          v2rayng_local=$(awk '/v2rayng/ {print$2}' version)
          caddy_local=$(awk '/caddy/ {print$2}' version)
          anxray_local=$(awk '/anxray/ {print$2}' version)
          sagernet_local=$(awk '/sagernet/ {print$2}' version)
          if ! [ "${anxray_latest}" == "${anxray_local}" ]; then
          rm anxray-"$anxray_local".apk
          wget -q --show-progress https://github.com/XTLS/AnXray/releases/latest/download/AX-"$anxray_latest"-arm64-v8a.apk -O android/anxray-"$anxray_latest".apk
          sed -i "s/anxray: $anxray_local/anxray: $anxray_latest/g" version
          sed -i "s/anxray-$anxray_local.apk/anxray-$anxray_latest.apk/g" README.md
          git add .
          git commit -am "anxray: ${anxray_local} -> ${anxray_latest}"
          push=1
          fi
          if ! [ "${sagernet_latest}" == "${sagernet_local}" ]; then
          rm sagernet-"$sagernet_local".apk
          wget -q --show-progress https://github.com/SagerNet/SagerNet/releases/latest/download/SN-"$sagernet_latest"-arm64-v8a.apk -O android/sagernet-"$sagernet_latest".apk
          sed -i "s/sagernet: $sagernet_local/sagernet: $sagernet_latest/g" version
          sed -i "s/sagernet-$sagernet_local.apk/sagernet-$sagernet_latest.apk/g" README.md
          git add .
          git commit -am "sagernet: ${sagernet_local} -> ${sagernet_latest}"
          push=1
          fi
          if ! [ "${v2rayn_latest}" == "${v2rayn_local}" ]; then
          rm v2rayn-v"$v2rayn_local".zip v2rayn-core-v"$v2rayn_local".zip
          wget -q --show-progress https://github.com/2dust/v2rayN/releases/latest/download/v2rayN.zip -O windows/v2rayn-v"$v2rayn_latest".zip
          wget -q --show-progress https://github.com/2dust/v2rayN/releases/latest/download/v2rayN-Core.zip -O windows/v2rayn-core-v"$v2rayn_latest".zip
          sed -i "s/v2rayn: $v2rayn_local/v2rayn: $v2rayn_latest/g" version
          sed -i "s/v2rayn-v$v2rayn_local.zip/v2rayn-v$v2rayn_latest.zip/g" README.md
          sed -i "s/v2rayn-core-v$v2rayn_local.zip/v2rayn-core-v$v2rayn_latest.zip/g" README.md
          git add .
          git commit -am "v2rayn: v${v2rayn_local} -> v${v2rayn_latest}"
          push=1
          fi
          if ! [ "${v2rayng_latest}" == "${v2rayng_local}" ]; then
          rm v2rayng-v"$v2rayng_local".apk
          wget -q --show-progress https://github.com/2dust/v2rayNG/releases/download/"$v2rayng_latest"/v2rayNG_"$v2rayng_latest"_arm64-v8a.apk -O android/v2rayng-v"$v2rayng_latest".apk
          sed -i "s/v2rayng: $v2rayng_local/v2rayng: $v2rayng_latest/g" version
          sed -i "s/v2rayng-v$v2rayng_local.apk/v2rayng-v$v2rayng_latest.apk/g" README.md
          git add .
          git commit -am "v2rayng: v${v2rayng_local} -> v${v2rayng_latest}"
          push=1
          fi
          if ! [ "${caddy_latest}" == "${caddy_local}" ]; then
          wget -q --show-progress https://github.com/caddyserver/caddy/releases/latest/download/caddy_"$caddy_latest"_linux_amd64.deb -O linux/caddy.deb
          sed -i "s/caddy: $caddy_local/caddy: $caddy_latest/g" version
          git add .
          git commit -am "caddy: v${caddy_local} -> v${caddy_latest}"
          push=1
          fi
          if ! [ "${xray_latest}" == "${xray_local}" ]; then
          wget -q --show-progress https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -O linux/xray-linux.zip
          wget -q --show-progress https://github.com/XTLS/Xray-core/releases/latest/download/Xray-windows-64.zip -O windows/xray-windows.zip
          sed -i "s#xray: $xray_local#xray: $xray_latest#g" version
          git add .
          git commit -am "xray: v${xray_local} -> v${xray_latest}"
          push=1
          fi
          if [ "$push" -eq 1 ]; then
          git push
          fi
