name: sync
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
      types: started
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check and release
        run: |
          bash sync.sh
